config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'
  get '/events', to: 'events#index'
  get '/events/new', to: 'events#new', as: 'new_event'
  get '/events/:id', to: 'events#show', as: 'event'
  post '/events', to: 'events#create'
  # get '/about', to: 'users#about', as: 'about'
  get '/attendance/new', to: 'attendance#new', as: 'new_attendance'
  post '/attendance', to: 'attendance#create'
  get '/attendance', to: 'attendance#index'
  delete '/attendance/:id', to: 'attendance#destroy'
  delete '/users/:id', to: 'users#destroy'
  # post '/events/:event_id/users', to: 'atendances#create', as: 'new_attendance'
  delete '/events/:id', to: 'events#destroy'
  resources :password_resets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances, dependent: :destroy
  has_many :users, through: :attendances
end

app/models/user.rb
class User < ApplicationRecord

  has_many :attendances, dependent: :destroy
  has_many :events, through: :attendances

  has_secure_password

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @events = @user.events
  end

  def create
    @event = Event.find(params[:event_id])
    if current_user.events.exists?(event_name: @event.event_name)
      flash[:notice] = "Event already in your calendar"
      redirect_to current_user
    else
    current_user.events << @event  # no error handling currently

    redirect_to current_user
    end
  end

  def destroy
    @event = current_user.events.find(params[:id])
    # @event.destroy
    current_user.events.delete(@event)
    flash[:notice] = "Successfully removed event."
    redirect_to user_path(current_user)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
      @events = Event.all
    end

    def new
      @event = Event.new
    end

    def create
      # @event = Event.create(event_params)
      # redirect_to events_path

      # @user = User.find(params[:user_id])
      # @event= Event.new(post_permit)
      # @user = User.find(params[:user_id])
      # @event = Event.find(params[:event_id])
      # @user.events << @event

      # if(@event.save)
      #   # @user.events << @event
      #   render json: @event
      # end
    end
    def add
      @user = User.find(params[:user_id])
      @event = Event.find(params[:event_id])
      @user.events << @event  # no error handling currently

      redirect_to current_user
    end

    def show
      @event= Event.find_by_id(params[:id])

    end

    def destroy
      @event = Event.find_by_id(params[:id])
      @event.destroy
      flash[:notice] = "Successfully removed event."
      redirect_to user_path(current_user)
    end

    def contact
      flash[:notice] = "We'll get back to you soon"
    end


    private

    def event_params
      params.require(:event).permit(:event_name, :event_location, :event_date, :event_url, :event_description, :event_image)
    end
    def post_permit
      params.permit(:event_name)
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController


  # request password reset.
  # you get here when the user entered his email in the reset password form and submitted it.
  def create
    @user = User.find_by_email(params[:email])

    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user

    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    redirect_to(login_path, :notice => 'Instructions have been sent to your email.')
  end


  # This is the reset password form.
  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end
  end

  # This action fires when the user has sent the reset password form.
  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end

    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)
    # confirm that email/password combination is correct
      @user = User.confirm(user_params)
      if @user
        login(@user)
        redirect_to @user
      else
        flash[:notice] = "Incorrect Email Address or Password"
        redirect_to login_path
      end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully logged out."        # <--- Add this flash notice
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]

  def index
    @users = User.all
    @user = User.new
  end

  def new
    @user= User.new
    redirect_to root_path
  end

  def create
    @user= User.new(user_params)
    if User.exists?(email: [@user.email])
      redirect_to login_path
      flash[:notice] = "User Exists!"
    else
      @user.save
      login(@user)
      redirect_to @user
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    @events = Event.all
    @event= Event.find_by_id(params[:id])
  end

  def destroy
    # only let current_user delete their own account
    if current_user == @user
      @user.destroy
      session[:user_id] = nil
      flash[:notice] = "Successfully deleted profile."
      redirect_to user_path(current_user)
    else
      redirect_to user_path(current_user)
    end
  end

  def about
  end


  def about
    # redirect_to about_path

  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
      session[:user_id] = user.id
      @current_user = user
    end

    def require_login

    end

    def current_user
      @current_user ||= User.find_by_id(session[:user_id])
    end

    def logout
      @current_user = session[:user_id] = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/index.html.erb
<div><%= @user.first_name %> is attending the following event</div>

<ul>
  <% @events.each do |event| %>
  <div>
    <h3><%= event.name %></h3>
    <% if current_user %>
      <%= button_to "Join", attendance_path(event) %>
    <% end %>
  </div>
  <br>
<% end %>
</ul>

app/views/events/index.html.erb

<div id="info"></div>

app/views/events/show.html.erb
<main class="row">
  <div class="col s4 card-panel offset-s1">
    <% random = Random.rand(1..7) %>
    <%= image_tag("#{random}.jpg")%>
  </div>
  <div class="col s6">
    <h3 class="center-align grey lighten-2 card-panel">Description</h3>
    <div class="event-page card-panel">
      <h3 class="center-align"><%= @event.event_name %></h3>
      <p class="center-align"> <%= @event.event_description %></p>
      <p><%= @event.event_date %></p>
      <%= button_to "Add", {:controller => :attendance, :action => 'create', :event_id => @event.id }, :method => :create, class: "btn grey sidebyside col" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventures</title>
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>

<body>
  <nav class="white">
    <div class="nav-wrapper">
      <%= link_to image_tag("logosample.jpeg"), root_path, class: "brand-logo" %>
      <ul id="nav-mobile" class="right hide-on-med-and-down ">
        <li>  <%= link_to "About Us", '/#about-us', class: "black-text" %></li>
        <li>  <%= link_to "Contact", '/#contact-us', class: "black-text" %></li>
        <% if current_user %>
        <li>  <%= link_to "Profile", user_path(current_user), class: "black-text" %></li>
        <li>   <%= link_to "Log Out", logout_path, class: "black-text grey lighten-2 btn" %></li>
        <% else %>
        <li> <%= link_to "Sign Up", new_user_path, class: "black-text" %></li>
        <li> <%= link_to "Log In", login_path, class: "black-text grey lighten-2 btn" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
  <main>
  <%= yield %>
</main>

  <footer class="page-footer center-align  teal lighten-2">
    <p>© Eventures Ltd.</p>
  </footer>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>

</html>

app/views/password_resets/edit.html.erb
<h1>Choose a new password</h1>
<%= form_for @user, :url => password_reset_path(@token), :html => {:method => :put} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= @user.email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<div class="row">
  <div class="col s4 offset-s4 card-panel ">
    <h3>Forgot Password</h3>
    <%= form_tag password_resets_path, :method => :post do %>
    <div class="field">
      <%= label_tag :email %><br />
      <%= text_field_tag :email %> <%= submit_tag "Reset my password!" %>
    </div>
  <% end %>
  </div>
</div>

app/views/users/index.html.erb
<!-- <img src="assets/pablo-unsplash.jpg"> -->
<header class="background">

<% if !current_user %>
<%= render '/users/partials/form' %>
<% end %>

</header>

<div class="row valign-wrapper">
  <p class="col s4 offset-s1 intro"><%= image_tag("logosample.jpeg")%>Eventure is an app that helps people socialize within the San Francisco Area. We provide and list the events and allow access to events. You will also be able to add the event to your calendar where you can view it on your profile. </p>
  <div class="col s5 offset-s2">
    <h4 class="card-panel grey darken-3 white-text center-align">Events around town</h4>
    <div id="info"></div>

  </div>
</div>
<%= render '/users/partials/about' %>
<%= render '/users/partials/contact' %>

app/views/users/new.html.erb
  <%= render '/users/partials/form' %>

app/views/users/partials/_about.html.erb
<div class="carousel" id="about-us">
  <h3 class="card-panel indigo darken-2 center-align white-text">About the team</h3>
  <div class="center-align carousel-item">
    <h5>Manjila Nakarmi</h5>
    <img src="assets/manjila_nakarmi.jpg" class="circle">
    <p>International Business graduate venturing into Web Development in the San Francisco Bay Area. Willing to learn new technologies and build on different skills. Would love to collaborate on new projects. Love to travel, ocassionally practice photography and be a foodie. Organized, grounded and a great communicator by nature.</p>
    <%= link_to "Github", "https://github.com/Manjilan", class: "black-text grey lighten-2 btn" %>
  </div>

  <div class="center-align carousel-item">
    <h5>Felix Chow</h5>
    <img src="assets/felix_chow.jpg" class="circle">
    <p>I am a web developer student who loves to learn new things and is willing to take challenges. I have not only taken web development classes, but also acquired multiple graphic design skills, because I want to become a good web designer. I want to apply all the knowledge I have learned to my web design career. In my spare time, I sing and play instruments, watch ice hockey.</p>
    <%= link_to "Github", "https://github.com/fchow2018", class: "black-text grey lighten-2 btn" %>
  </div>

  <div class="center-align carousel-item">
    <h5>Terrence Langston</h5>
    <img src="assets/terrence_langston.jpg" class="circle">
    <p>No matter the obstacle, I plan to achieve great things in my life and continue learning. I have acquired a set of skills that allows me to bring value to a companies success and also my own. I look for positive vibes in every environment, and if it doesn't exist I'll create it. General Assembly Web Development Immersive has gave me a new joy on technology and web development in general.</p>
    <%= link_to "Github", "https://github.com/ttime1100", class: "black-text grey lighten-2 btn" %>
  </div>

  <div class="center-align carousel-item">
    <h5>Juan Carlos</h5>
    <img src="assets/juan_carlos.jpeg" class="circle">
    <p>Systems thinking. Elegant design. Data as a story waiting to be told. These are some of my interest and motivations to delve into Front-end development.</p>
    <%= link_to "Github", "https://github.com/juancarlucci", class: "black-text grey lighten-2 btn" %>
  </div>
</div>

app/views/users/partials/_contact.html.erb
<div class="row light-blue darken-2 valign-wrapper" id ="contact-us">
<div class= "col s6 offset-s3 white center-align card-panel contact-us">
    <h3>Contact Us</h3>
      <input placeholder="Full Name">
      <input placeholder="Email Address">
      <input placeholder="Message">
      <%= button_to "Submit", :method => 'contact', class: "grey sidebyside col" %>
  </div>
</div>

app/views/users/partials/_form.html.erb
<div class="row">
<div class= "col s5 offset-s7 white center-align sign-up">
<%= form_for @user do |f|%>
<h2 class ="center-align">Sign Up</h2>

    <%= f.text_field :first_name, placeholder: "First Name" %>


    <%= f.text_field :last_name, placeholder: "Last Name" %>


    <%= f.text_field :email, placeholder: "Email" %>


    <%= f.password_field :password, placeholder: "Password" %>

  <%= f.submit "Sign Up", class: "center-align white-text grey lighten-2 btn" %>
  <% flash.each do |key, value| %>
  <div class="red-text alert alert-<%= key %>"><%= value %></div>
  <% end %>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="header">
  <h4>Welcome, <%= @user.first_name %></h4>

</div>

<main class="row" id = "show-main">
  <div class="col s4 offset-s1">
    <div class= "myevents">
      <h4 class="card-panel grey white-text center-align showpanel">My Events</h4>
      <!-- Events -->
      <div id="event_list">
        <% @user.events.each do |event| %>
        <div class="row event-row card-panel grey lighten-2">
          <p class= "sidebyside col"><%= link_to event.event_name, event_path %> <%= event.event_date %></p>
          <%= button_to "X", {:controller => :attendance, :action => 'destroy', :id => event.id }, :method => :delete, class: "btn-floating pulse grey sidebyside col" %>
        </div>
        <% end %>
      </div>

    </div>

  </div>

  <!-- <div id="calendar"> -->
    <!--Calendar  -->
    <!-- <%= form_tag("/search", method: "get") do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
    <% end %> -->
  <!-- </div> -->




  <aside class="col s6 offset-s0.5">

    <h4 class="card-panel grey white-text center-align showpanel">Events around town</h4>
    <% @events.each do |event| %>
    <div class="row event-row card-panel grey lighten-2">
      <% random = Random.rand(1..7) %>
      <%= image_tag("#{random}.jpg", class: "event-image col")%>
      <p class= "sidebyside col"><%= link_to event.event_name, event %>  <%= event.event_date %></p>
      <%= button_to "+", {:controller => :attendance, :action => 'create', :event_id => event.id }, :method => :create, class: "btn-floating pulse grey sidebyside col" %>

    </div>
    <% end %>



  </aside>

</main>